package co.edu.udistrital.model;

public class ListaDatos {

    private static String[] OFICIOS = {
        //Lista generada gracias a chatgpt
        "apacentar ovejas",
        "ordeñar ovejas",
        "esquilar lana",
        "curar ovejas",
        "vigilar el rebaño",
        "proteger del lobo",
        "conducir el ganado",
        "alimentar corderos",
        "vigilar nacimientos",
        "separar ovejas enfermas",
        "marcar ovejas",
        "contar el rebaño",
        "enseñar a perros pastores",
        "adiestrar perros de guardia",
        "reparar corrales",
        "limpiar establos",
        "cortar pasto",
        "regar pastizales",
        "buscar agua",
        "abrir pozos",
        "construir cercas",
        "vigilar pastos",
        "trasladar ganado",
        "planear trashumancia",
        "organizar caravana",
        "vigilar campamento",
        "hacer guardia nocturna",
        
        "negociar lana",
        "vender leche",
        "hacer queso",
        "hacer yogur",
        "curar quesos",
        "preparar mantequilla",
        "producir cuajada",
        "comercializar carne",
        "sacrificar ovejas",
        "salazonar carne",
        "curtir pieles",
        "fabricar cuero",
        "coser cuero",
        "fabricar botas",
        "hacer sogas",
        "tejer lana",
        "teñir lana",
        "hacer mantas",
        "hacer ponchos",
        "hacer alfombras",
        "hacer tapices",
        
        "construir chozas",
        "reparar chozas",
        "fabricar adobes",
        "levantar muros",
        "blanquear paredes",
        "reparar molinos",
        "hacer herramientas de madera",
        "tallar bastones",
        "hacer cucharas",
        "hacer arcos",
        "fabricar flechas",
        "preparar trampas",
        "construir balsas",
        "reparar puentes",
        
        "preparar pan",
        "recolectar leña",
        "encender hogueras",
        "cocinar sopas",
        "hacer guisos",
        "asar carne",
        "preparar caldos",
        "hacer infusiones",
        "preparar vino",
        "servir vino",
        "hacer aguardiente",
        "almacenar granos",
        "cuidar huertas",
        "cultivar heno",
        "cultivar trigo",
        "cosechar cebada",
        "molinar trigo",
        
        "vigilar montañas",
        "vigilar valles",
        "vigilar ríos",
        "vigilar tormentas",
        "resguardar animales",
        "vigilar sequías",
        "leer señales del clima",
        "interpretar vientos",
        "predecir lluvias",
        "avisar tormentas",
        "vigilar frontera",
        "vigilar bandoleros",
        "vigilar caminos",
        "vigilar cañadas",
        
        "cantar canciones",
        "contar cuentos",
        "tocar cuerno",
        "tocar flauta",
        "tocar zampoña",
        "inventar canciones",
        "escribir versos",
        "enseñar cantos",
        "hacer danzas",
        "organizar fiestas",
        "narrar leyendas",
        "componer poemas",
        
        "enseñar oraciones",
        "rezar por lluvias",
        "rezar por cosechas",
        "bendecir animales",
        "dar consejo espiritual",
        "acompañar entierros",
        "ayudar en bodas",
        "acompañar enfermos",
        "cuidar ancianos",
        "ser guía espiritual",
        
        "buscar plantas medicinales",
        "curar heridas",
        "hacer pomadas",
        "acompañar enfermos",
        "curar con hierbas",
        "vigilar partos de animales",
        "dar primeros auxilios",
        "hacer masajes",
        
        "cazar conejos",
        "cazar liebres",
        "cazar zorros",
        "ahuyentar lobos",
        "pescar truchas",
        "pescar bagres",
        "cuidar trampas de pesca",
        
        "enseñar a niños pastoreo",
        "enseñar a niños canciones",
        "contar historias del campo",
        "dar consejos",
        "resolver disputas",
        "guiar caminantes",
        "ayudar viajeros",
        "mostrar caminos",
        "llevar mensajes",
        "ser correo rural",
        
        "contar estrellas",
        "vigilar luna",
        "marcar estaciones",
        "medir sombras",
        "predecir eclipses",
        "usar calendario lunar",
        
        "cuidar cabras",
        "cuidar vacas",
        "guiar mulas",
        "vigilar burros",
        "adiestrar caballos",
        "cuidar gallinas",
        "recoger huevos",
        "vigilar pavos",
        "cuidar perros",
        "cuidar gatos del establo",
        
        "cuidar sementeras",
        "ahuyentar aves",
        "vigilar espantapájaros",
        "cuidar fuego",
        "recoger agua del pozo",
        "transportar agua",
        "hacer barro",
        "preparar sal",
        "dar sal a ovejas",
        "hacer carbón",
        "fabricar instrumentos",
        "inventar herramientas",
        "abrir trochas",
        "explorar caminos",
        "cuidar puentes",
        "vigilar ganado ajeno",
        "prestar ayuda a vecinos",
        "acompañar caravanas",
        "organizar trueques",
        "intercambiar productos",
        "vender carne seca",
        "guardar salazones",
        "administrar campamento",
        "cuidar niños",
        "enseñar artes del campo",
        "hacer esculturas de madera",
        "pintar símbolos",
        "marcar ganado con hierro",
        "escribir registros de animales",
        "contar ovejas cada día",
        "calcular lana producida",
        "planear rutas de pastoreo",
        "trazar mapas de pastos",
        "inventariar recursos",
        "planear refugios móviles",
        "construir carretas",
        "manejar carretas",
        "vigilar caminos reales",
        "espiar movimientos enemigos",
        "llevar noticias al pueblo",
        "dar aviso de guerras",
        "acompañar soldados",
        "curar heridos de batalla",
        "guardar secretos",
        "servir de mensajero diplomático",
        "llevar presentes",
        "guiar peregrinos",
        "vigilar templos rurales",
        "mantener orden en fiestas",
        "cuidar reliquias",
        "encender cirios",
        "cantar himnos",
        "vigilar procesiones",
        "organizar romerías",
        "recibir forasteros",
        "dar hospedaje",
        "ofrecer comida",
        "acompañar viajeros de noche",
        "proteger mercaderes",
        "negociar tributos",
        "cuidar tesoros comunales",
        "repartir ofrendas",
        "guardar documentos",
        "contar diezmos",
        "vigilar campos comunales",
        "administrar justicia local",
        "resolver disputas de tierras",
        "defender derechos de pastores",
        "reunir a la comunidad",
        "convocar a consejo",
        "dirigir asambleas",
        "redactar acuerdos",
        "enseñar escritura",
        "enseñar lectura",
        "enseñar cuentas",
        "hacer cálculos de cosecha",
        "inventar canciones épicas",
        "cantar genealogías",
        "memorizar linajes",
        "relatar historias sagradas"
    };

	public String[] getOFICIOS() {
		return OFICIOS;
	}

}
